#if !defined(CONFIG_HPP)
#define CONFIG_HPP

#define BOOST_SPIRIT_ACTIONS_ALLOW_ATTR_COMPAT 1
#define BOOST_SPIRIT_UNICODE
#define BOOST_SPIRIT_USE_PHOENIX_V3 1
#define BOOST_SPIRIT_NO_PREDEFINED_TERMINALS

#endif
