% Automatically generated by BMC, the braille music compiler
\version "2.14.2"
\include "articulate.ly"
music =
  <<
    \new PianoStaff <<
      \new Staff = "RH" {
        \clef "treble"
        \key g \major
        \time 4/4
        \repeat volta 2 {
          r4 r32 g' a' b' c'' d'' e'' fis'' g''8. d''16 b'8. g'16 |
          d''4.\mordent  e''8 c''4~ c''8~ c''32 b' c'' d'' |
          g'8. g''32 fis'' g''8. e''16 \appoggiatura d''8 cis''8. b''16 a''8. g''16 |
          << {fis''4.-4 g''8}\\{d''4-1 r} >> \appoggiatura g''8 a''2~ |
          a''8~ a''32 a'' g'' fis'' g''8. d''16~ << {\appoggiatura e''8 f''4.\mordent  g''8-5}\\{d''2} >> |
          \appoggiatura f''8 <e''~^\markup { \finger "3 - 4" } c''>8 e''32 d'' c'' b' c''8~-4 c''32 b' a' g' a'8. a'16-1 g''8.\mordent  g''16 |
          <g''~-4 d'' fis'>4 g''32 b'' a'' g'' fis'' e'' d''-2 c'' a''8. c''16 a''8. c''16 |
          b'4~-3 b'8~ b'32 a' g'-3 fis' g'16-1[ d''-.-2 e''-. fis''-.] g''-.[ fis''-.-2 g''-. a''-.] |
          b''8~ b''32 a'' g'' fis'' g''8~ g''32 fis'' e'' dis''-2 e''8. b'16 cis''8.\mordent  <d'' b'>16 |
          << {\appoggiatura d''8-3 cis''8~ cis''32 e''-4 fis''-3 g'' a''8. a''16 a''4~ a''8~ a''32 a'' g'' fis''}\\{a'4 r8 r16 a'' dis''8. fis''16 b'4~} >> |
          << {g''8~-5 g''32 fis'' e'' dis'' e''8. b''16 d''4. cis''16 b'}\\{b'4 r b'2} >> |
          << {cis''8~-4 cis''32 d'' cis''-2 d'' d''8. cis''32 d'' e''4~^\markup { \finger "4 - 5" } e''32[ d'' cis'' b' a' g'-4 fis' e']}\\{a'4^\markup { \finger "2 - 1" } b' cis'' r} >> |
          d'8. fis'16 a'8.\mordent -3 b'16( <c''~ a' d'>4 c''8~) c''32 c''-3 b' a' |
          b'8~ b'32 cis'' d'' e'' d''8~ d''32 cis'' d'' e'' a'8~ a'32 e''-2 fis'' g'' a''8. cis''16-2( |
          d''4.-4-1) e''8-3 << {e''4. d''8}\\{cis''2-1} >> |
        }
        \alternative {
          {<d'' a' c'>1  | }
          { \time 3/8 d''8-1 a''16-4 g'' fis'' e'' | }
        }
        \repeat volta 2 {
           fis''8 g''\turn  a'' |
          d''16[ fis''-3 e'' g'' fis'' a''] |
          g''8 fis'' g''-5 |
          << {e''8-3 dis'' e''}\\{c''4.~-1} >> |
          << {a''4.~}\\{c''16[ g'' fis'' e''-1 dis''-2 e'']} >> |
          << {a''8 g''16 e'' fis'' dis''}\\{b'4.~} >> |
          << {b''4.~}\\{b'16[ cis'' dis'' e''-1 fis''-3 dis''-2]} >> |
          << {b''16[ c'''-4 b'' a'' g'' fis''-2]}\\{e''8 r r} >> |
          g''16[ e'' a'' e'' b'' e''] |
          c'''16[ b'' a'' g''-1 fis''-4 e''] |
          << {d''16[ fis'' e'' g'' fis''-3 a'']}\\{a'8 b' c''} >> |
          << {g''16-3 a'' a''8. g''32 a''}\\{d''8 e'' fis''} >> |
          <b'' g''>4 <g''-5 d''>8 |
          <e''-4 g'>8 <fis'' a'> <dis'' fis'> |
          << {e''4 r8}\\{g'8 gis'8. fis'32 gis'} >> |
          << {r8 e''16 d'' c'' b'-1}\\{a'4-1  gis'8-1} >> |
          << {c''8-3 d'' e''}\\{a'8-2 g'4} >> |
          << {a'16-2[ c'' b'-1 d'' cis'' e'']}\\{ fis'8-2 g'  e'} >> |
          << {d''32-1 e'' fis''16 fis''8. e''32 fis''}\\{fis'16 r r8 r} >> |
          g''8 fis''16 e'' d'' c''-2 |
          b'16[ d'' c'' e'' d'' f''] |
          << {e''4.~^\markup { \finger "4 - 5" }}\\{r8 fis'-2 g'\turn } >> |
          << {e''16[ d'' c'' b' c''-1 fis'']}\\{a'8 r r} >> |
          a''16[ d''-2 c'' b'-3 c'' a'] |
          b'16-1[ e''-4 d'' c'' d''-1 gis''] |
          b''16[ e''-2 d'' c''-2 d'' b'] |
          << {c''4.~-5}\\{r16[ g'-3 fis' g' a' fis']} >> |
          << {c''16[ b' a' b' c'' a']}\\{d'4.~} >> |
          << {d''4 b'8-5}\\{d'16 fis' e' g'-3 fis'8} >> |
          <g'-4 b>8 <a' c'> <fis' a> |
        }
        \alternative {
          {<g' b>4 r8 | r8 a''16-4 g'' fis'' e''  | }
          { \time 4/4 <g' d' fis>1 | }
        }
      }
      \new Staff = "LH" {
        \clef "bass"
        \key g \major
        \time 4/4
        \repeat volta 2 {
          << {g,4 r r r8 r16 g-2}\\{<b, d b>4 r r r8 r16 b} >> |
          <fis~ a>4 fis32 d e fis g a b c' d'8. a16 fis8. d16 |
          e4. g8-1 e4~ e8~ e32 d e fis |
          d8. c'32 b c'8. a16 fis8.-5 e'16 d'8. c'16 |
          b4.-1 b8 b~ b32 c' b a b8. g16 |
          c'4~\mordent  c'8~-2 c'32 d' c' b c'8~-1 c'32 b a g a8~-1 a32 g fis e |
          d2~^\markup { \finger "5 - 1" } d16 c32 b, a,-1 g, fis, e, d,16[ fis, a, d] |
          g,16-.[ d-.-1 e-.-3 fis-.] g-.[ fis-. g-. a-.-3] b4~ b8~ b32 a-1 g fis |
          g16-.[ b-. cis'-.-3 dis'-.] e'-.[ dis'-.-4 e'-. fis'-.] g'8. g16 g'8. g'16-2 |
          g'4~-1 g'8~ g'32 g' fis' e' fis'8~ fis'32 b cis' dis' e'8. e'16-1 |
          e'4~-2 e'8~ e'32 c'-1 b a gis8. b16-1 e8. gis16 |
          a4~-1 a16 a,32 b, cis d e fis-2 g8. e16 cis8. a,16 |
          fis4~-2 fis8~ fis32 g fis e d8~-1 d32 c b, a, g,8~ g,32 d e-3 fis |
          << {g8.\mordent  g,16 g8. g16-4 g4~-4 g8~ g32 g-2 fis e}\\{r4 r8 r16 b cis'4 r} >> |
          fis16~ fis32 d e fis g a b8.-2 g16 a4-1 a,-2 |
        }
        \alternative {
          {d,4~ d,16 d32 e-3 fis g a-3 b c'8. a16 fis8. d16  | }
          { \time 3/8 d,4 r8 | }
        }
        \repeat volta 2 {
          << { R1*3/8}\\{r8 d''16-1 c'' b' a'} >> |
          << {R1*3/8}\\{b'8 c'' d''} >> |
          << {R1*3/8}\\{g'16[ b' a' c'' b' d'']} >> |
          << {R1*3/8}\\{r8 a'16-1 g' fis' e'} >> |
          << {R1*3/8}\\{fis'8 g' a'} >> |
          << {R1*3/8}\\{dis'16-4[ fis' e' g' fis'-4 a']} >> |
          << {r8 b16-3 a g fis-4}\\{g'8-1 fis'-1 r} >> |
          << {g8-5 a-4 b-3}\\{r8 e' dis'-2} >> |
          << {e16[ g fis a g-5 b]}\\{e'4.~} >> |
          << {a8 b c'-1}\\{e'4 r8} >> |
          fis16-4[ a g b a-4 c'] |
          b8 c' d' |
          g16-5[ b a c' b d'] |
          c'8 a b-1 |
          << {e8 r r}\\{r8 e'16 d'-3 c' b} >> |
          c'8 d' e'-2 |
          a16-5[ c' b d' cis' e'] |
          d'4.~-4 |
          << {r8 d16-2 c b, a,}\\{d'8 r r} >> |
          << {b,8 c d-2}\\{r8 g fis} >> |
          << {g,16[ b, a, c b,-4 d]}\\{g4.~} >> |
          << {c16[ b, a,-1 g, fis, e,]}\\{g8 r r} >> |
          fis,8 g,\turn  a, |
          d,16[ fis, e, g, fis, a,] |
          g,8-3 a,\turn  b, |
          e,16[ gis, fis, a, gis, b,] |
          a,16-5[ e a g fis e] |
          fis16[ g fis e-1 d c] |
          b,16[ d c e d-4 fis] |
          e8 c d-1 |
        }
        \alternative {
          {g,16-3[ fis, g, a, b, c-2] | d8 d, r  | }
          { \time 4/4 g,1 | }
        }
      }
    >>
  >>

\score {
  \music
  \layout { }
}
\score {
  \unfoldRepeats \articulate \music
  \midi { }
}
