% Automatically generated by BMC, the braille music compiler
\version "2.14.2"
\include "articulate.ly"
\header {
  tagline = ""
}
music =
  <<
    \new Staff {
      \key f \major
      \time 6/8
      f'8 f' a' c''8. a'16 c''8 | % 1
      \clef F f,8 g, a, bes,4. | % 2
    }
  >>

\score {
  \music
  \layout { }
}
\score {
  \unfoldRepeats \articulate \music
  \midi { }
}
