% Automatically generated by BMC, the braille music compiler
\version "2.14.2"
\include "articulate.ly"
\header {
  tagline = ""
}
music =
  <<
    \new Staff {
      \time 3/4
      <g'' g' d' f>4 <g'' c'' a' b> <f'' d'' e' a> | % 1
      <e'' c'' e' c'>2. | % 2
    }
  >>

\score {
  \music
  \layout { }
}
\score {
  \unfoldRepeats \articulate \music
  \midi { }
}
