% Automatically generated by BMC, the braille music compiler
\version "2.14.2"
\include "articulate.ly"
\header {
  tagline = ""
}
music =
  <<
    \new Staff {
      \time 2/4
      g'4( a'8 b' | % 1
      c''4 d''8 e'' | % 2
      f''4 e''8 d'' | % 3
      e''4 c''8) r | % 4
    }
  >>

\score {
  \music
  \layout { }
}
\score {
  \unfoldRepeats \articulate \music
  \midi { }
}
