% Automatically generated by BMC, the braille music compiler
\version "2.14.2"
\include "articulate.ly"
\header {
  tagline = ""
}
music =
  <<
    \new Staff {
      \clef "treble"
      \time 6/8
      c'8 e' g' a'4 c''8 | % 1
      d''8 f'' a'' b'' d''' f''' | % 2
      e'''8 g''' b''' c'''' a''' f''' | % 3
      d'''8 b'' g'' f'' d'' b' | % 4
      g'4 f'8 d'4 e'8 | % 5
      c'2. | % 6
    }
  >>

\score {
  \music
  \layout { }
}
\score {
  \unfoldRepeats \articulate \music
  \midi { }
}
